development:
  shield:
    endpoint_url: http://localhost:3000
    image_base_url: http://s3.amazonaws.com/mines.edu/cs446/programeurs/development/photos
    image_default_url: http://localhost:3000/images/default_shield.png
  harvester:
    endpoint_url: http://localhost:3000
    image_base_url: http://s3.amazonaws.com/mines.edu/cs446/programeurs/development/photos
    image_default_url: http://localhost:3000/images/default_shield.png
  fighter:
    endpoint_url: http://localhost:3000
    image_base_url: http://s3.amazonaws.com/mines.edu/cs446/beardos/development/photos
    image_default_url: http://localhost:3000/images/default_fighter_thumb.png
  battleship:
    endpoint_url: http://localhost:3000
    image_base_url: http://s3.amazonaws.com/mines.edu/cs446/giraffe/development/images
    image_default_url: http://localhost:3000/images/default_battleship.png
  destroyer:
    endpoint_url: http://localhost:3000
    image_base_url: http://s3.amazonaws.com/mines.edu/cs446/vegetarians/development/images
    image_default_url: http://localhost:3000/images/default_destroyer.jpg
  puppy:
    endpoint_url: http://localhost:8080
    image_base_url: http://s3.amazonaws.com/mines.edu/cs446/bidoof/development/photos
    image_default_url: http://localhost:8080/images/default_puppy.png
  corvette:
    endpoint_url: http://localhost:3000
    image_base_url: http://s3.amazonaws.com/mines.edu/cs446/illogicians/development/photos
    image_default_url: http://localhost:3000/images/default_corvette.png
  velociraptor:
    endpoint_url: http://localhost:3000
    image_base_url: http://s3.amazonaws.com/mines.edu/cs446/hipsters/development/photos
    image_default_url: http://localhost:3000/images/default_velociraptor.png
  missile:
    endpoint_url: http://localhost:3000
    image_base_url: http://s3.amazonaws.com/mines.edu/cs446/bacon/development/photos
    image_default_url: http://localhost:3000/images/default_missile.png

staging:
  shield:
    endpoint_url: http://mines:mines@afternoon-mist-423.heroku.com
    image_base_url: http://s3.amazonaws.com/mines.edu/cs446/programeurs/staging/photos
    image_default_url: http://mines:mines@afternoon-mist-423.heroku.com/images/default_shield.png
  harvester:
    endpoint_url: http://dragon:1234@growing-sword-776.heroku.com
    image_base_url: http://s3.amazonaws.com/mines.edu/cs446/dragon/staging/photos
    image_default_url: http://dragon:1234@growing-sword-776.heroku.com/images/default.png
  fighter:
    endpoint_url: http://mines:mines@deep-sky-83.heroku.com
    image_base_url: http://s3.amazonaws.com/mines.edu/cs446/beardos/staging/photos
    image_default_url: http://mines:mines@deep-sky-83.heroku.com/images/default_fighter_thumb.png
  battleship:
    endpoint_url: http://user:password@high-winter-98.heroku.com
    image_base_url: http://s3.amazonaws.com/mines.edu/cs446/giraffe/staging/images
    image_default_url: http://user:password@high-winter-98.heroku.com/images/default_battleship.png
  destroyer:
    endpoint_url: http://mines:mines@quiet-fog-435.heroku.com/
    image_base_url: http://s3.amazonaws.com/mines.edu/cs446/vegetarians/staging/images
    image_default_url: http://mines:mines@quiet-fog-435.heroku.com/images/default_destroyer.jpg
  puppy:
    endpoint_url: http://username:password@warm-warrior-421.heroku.com
    image_base_url: http://s3.amazonaws.com/mines.edu/cs446/bidoof/staging/photos
    image_default_url: http://username:password@warm-warrior-421.heroku.com/photos/default_puppy.png
  corvette:
    endpoint_url: http://severe-autumn-903.heroku.com
    image_base_url: http://s3.amazonaws.com/mines.edu/cs446/illogicians/staging/photos
    image_default_url: http://severe-autumn-903.heroku.com/photos/default_corvette.png
  velociraptor:
    endpoint_url: http://sharp-planet-461.heroku.com/
    image_base_url: http://s3.amazonaws.com/mines.edu/cs446/hipsters/staging/photos
    image_default_url: http://sharp-planet-461.heroku.com//photos/default_velociraptor.png
  missile:
    endpoint_url: http://heffalumps:woozles@evening-sky-370.heroku.com
    image_base_url: http://s3.amazonaws.com/mines.edu/cs446/bacon/staging/photos
    image_default_url: http://heffalumps:woozles@evening-sky-370.heroku.com/photos/default_missile.png

production:
  shield:
    endpoint_url: http://simple-dawn-803.heroku.com
    image_base_url: http://s3.amazonaws.com/mines.edu/cs446/programeurs/production/photos
    image_default_url: http://simple-dawn-803.heroku.com/images/default_shield.png
  harvester:
    endpoint_url: http://morning-window-839.heroku.com
    image_base_url: http://s3.amazonaws.com/mines.edu/cs446/dragon/production/photos
    image_default_url: http://morning-window-839.heroku.com/images/default.png
  fighter:
    endpoint_url: http://blooming-wind-193.heroku.com
    image_base_url: http://s3.amazonaws.com/mines.edu/cs446/beardos/production/photos
    image_default_url: http://blooming-wind-193.heroku.com/images/default_fighter_thumb.png
  battleship:
    endpoint_url: http://young-moon-201.heroku.com
    image_base_url: http://s3.amazonaws.com/mines.edu/cs446/giraffe/production/images
    image_default_url: http://young-moon-201.heroku.com/images/default_battleship.png
  destroyer:
    endpoint_url: http://high-lightning-781.heroku.com/
    image_base_url: http://s3.amazonaws.com/mines.edu/cs446/vegetarians/production/images
    image_default_url: http://high-lightning-781.heroku.com/images/default_destroyer.jpg
  puppy:
    endpoint_url: http://pure-frost-854.heroku.com
    image_base_url: http://s3.amazonaws.com/mines.edu/cs446/bidoof/production/photos
    image_default_url: http://pure-frost-854.heroku.com/images/default_puppy.png
  corvette:
    endpoint_url: http://evening-sky-672.heroku.com
    image_base_url: http://s3.amazonaws.com/mines.edu/cs446/illogicians/production/photos
    image_default_url: http://evening-sky-672.heroku.com/photos/default_corvette.png
  velociraptor:
    endpoint_url: http://pure-journey-944.heroku.com/
    image_base_url: http://s3.amazonaws.com/mines.edu/cs446/hipsters/production/photos
    image_default_url: http://pure-journey-944.heroku.com/photos/default_velociraptor.png
  missile:
    endpoint_url: http://vivid-dusk-329.heroku.com
    image_default_url: http://vivid-dusk-329.heroku.com/photos/default_missile.png
    image_base_url: http://s3.amazonaws.com/mines.edu/cs446/bacon/production/photos
